name: Docker Image (pre-release)

on:
  push:
    branches: [ pre-release ]
    
env:
  DOTNET_VERSION: '9.0.x' # The .NET SDK version to use

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Test Cases
    
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: openbudgeteer
          MARIADB_USER: openbudgeteer
          MARIADB_PASSWORD: openbudgeteer
          MARIADB_ROOT_PASSWORD: openbudgeteer
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Install Blazor dependencies
        run: dotnet restore OpenBudgeteer.Blazor
        
      - name: Build Blazor
        run: dotnet build OpenBudgeteer.Blazor --configuration Release --no-restore
        
      - name: Run Core Test Cases
        env:
          CONNECTION_PROVIDER: mariadb
          CONNECTION_SERVER: localhost
          CONNECTION_PORT: 3306
          CONNECTION_USER: openbudgeteer
          CONNECTION_PASSWORD: openbudgeteer
          CONNECTION_DATABASE: openbudgeteer
        run: dotnet test OpenBudgeteer.Core.Test
        
  deploy-docker-app:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image (App)
    needs: test
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: axelander/openbudgeteer:pre-release
          platforms: linux/arm64,linux/amd64
          
  deploy-docker-api:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image (API)
    needs: test
    if: success()
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: axelander/openbudgeteer-api:pre-release
          file: API.Dockerfile
          platforms: linux/arm64,linux/amd64